services:
  - docker

jobs:
  include:
    - stage: build
      script: ./batect run build

    - stage: unit test
      script: ./batect run unitTest

    - stage: integration test
      script: ./batect run integrationTest

    - stage: journey test
      # The build step below is required until batect supports specifying dependencies between tasks.
      script: ./batect run build && ./batect run journeyTest
