services:
  - docker

jobs:
  include:
    - stage: build
      script: ./batect build

    - stage: unit test
      script: ./batect unitTest

    - stage: integration test
      script: ./batect integrationTest

    - stage: journey test
      # The build step below is required until batect supports specifying dependencies between tasks.
      script: ./batect build && ./batect journeyTest