services:
  - docker

jobs:
  include:
    - stage: build
      script: ./batect run build

    - stage: unit test
      script: ./batect run unitTest

    - stage: integration test
      script: ./batect run integrationTest

    - stage: journey test
      script: ./batect run journeyTest

    - stage: push image
      script: ./batect run pushImage

before_cache:
  - rm -f  .gradle-cache/caches/modules-2/modules-2.lock
  - rm -fr .gradle-cache/caches/*/plugin-resolution/
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.bin
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - .gradle-cache/caches/
    - .gradle-cache/wrapper/
